---
# configure tasks file for android_studio
- name: Increase inotify max_user_watches
  become: yes
  sysctl:
    name: fs.inotify.max_user_watches
    value: "{{ android_studio_inotify_max_user_watches }}"
    sysctl_file: "{{ inotify_sysctl_file }}"
