---
# safe uninstall tasks file for android_studio
- name: Stat of install directory
  become: yes
  stat:
    path: "{{ install_dest_full }}"
  register: as_install_dir_stat

- name: Safe uninstall
  become: yes
  block:
    - name: Include unarchive tasks
      include_tasks: unarchive.yml
      when: not ansible_check_mode

    - name: Install rsync for synchronize module
      package:
        name:
          - rsync
        state: present
      notify: Remove rsync

    - name: Compare unarchived content with installed
      synchronize:
        src: "{{ android_studio_temp_dir.path }}/{{ top_src_name }}/"
        dest: "{{ install_dest_full }}/"
        checksum: yes
        times: no
        delete: no
      check_mode: yes
      delegate_to: "{{ inventory_hostname }}"
      register: rsync_result
      when: not ansible_check_mode

    - name: Fail if the installed content doesn't match with the unarchived
      fail:
        msg: Installed content doesn't match with archive content
      when:
        - not ansible_check_mode
        - rsync_result.changed

    - name: Remove installed content
      file:
        name: "{{ install_dest_full }}"
        state: absent
  when: as_install_dir_stat.stat.exists

- name: Check if a desktop entry exists
  become: yes
  stat:
    path: "{{ desktop_file_full }}"
  register: as_desktop_entry_stat

- name: Safe uninstall of the desktop entry
  become: yes
  block:
    - name: Include desktop entry tasks
      include_tasks: desktop_entry.yml

    - name: Check desktop file is same
      copy:
        src: "{{ tmp_desktop_file_full }}"
        dest: "{{ desktop_file_full }}"
        remote_src: yes
      check_mode: yes
      register: android_studio_desktop_check

    - name: Fail if content of installed desktop entry doesn't match with created one
      fail:
        msg: Installed desktop file does not match created desktop file
      when: android_studio_desktop_check.changed

    - name: Remove installed desktop file
      file:
        name: "{{ desktop_file_full }}"
        state: absent
  when: not ansible_check_mode and as_desktop_entry_stat.stat.exists
