---
# uninstall tasks file for android_studio
- name: Remove installed content
  become: yes
  file:
    name: "{{ install_dest_full }}"
    state: absent

- name: Remove installed desktop file
  become: yes
  file:
    name: "{{ desktop_file_full }}"
    state: absent
